name: Observability - Trial

on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push trial 
        id: docker_build_trial
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./project/reference-app/trial
          file : ./project/reference-app/trial/Dockerfile
          platforms: linux/amd64
          tags: rfrodriguez/observability-trial:latest
